### ISSUE TITLE
Body text styles

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_catering#10]
### Location

Featured cards/Global
### Description

Color should be Ukrop's-brown and should be Gotham Book.
### Screenshot

![screen shot 2016-10-19 at 2 58 02 pm](https://cloud.githubusercontent.com/assets/17103891/19533117/79b48756-960c-11e6-9a2e-530c82d394f0.png)

**Comment by caitlynmayers** [comment]
Fix verified.
