### ISSUE TITLE
Header logo placement on mobile

### ISSUE THREAD

**Issue by kevinjflores** [tfuqua/ukrops_catering#5]
### Location

Header
### Description

In mobile view: Change placement of header logo to left-justified
### Screenshot

![image](https://cloud.githubusercontent.com/assets/22937737/19526107/4d5c4df8-95f1-11e6-9e99-d8163f4c5ef9.png)

**Comment by caitlynmayers** [comment]
@tfuqua can you nudge the padding-left so it is in line with the edge of the feature area box underneath it?

**Comment by tfuqua** [comment]
yep. will do right now

**Comment by tfuqua** [comment]
This has been deployed

**Comment by caitlynmayers** [comment]
Fix verified.
